openapi: 3.0.0
info:
  title: todo
  description: todo app API
  version: 0.1.9

servers:
  - url: https://web-production-ec13.up.railway.app/api
    description: todo server
  - url: http://localhost:3000/api
    description: local server
paths:
  /all:
    get:
      tags:
        - todo
      responses:
        "200":
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
